version: "3.8"
services:
  server:
    image: validation
    ports:
      - "8089:8089"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=achatdb  

networks:
  springmysql-net:
